### ISSUE TITLE
Does not correctly handle delayed response from the email verifier API

### ISSUE THREAD

**Issue by NikolaiGulatz** [prospectio/hunterio#1]
According to the hunter.io API docs when a lookup times out the API returns a 202 status code and no data. This leads to a `NoMethodError - undefined method 'merge!' for nil:NilClass` in the `call_api` method of `email_verifier.rb` since it assumes that data is always present when the request was successful.

Whether or not a request is treated as successful depends on the used Faraday version which hunter.io does not specify explicitly. In the latest Faraday version  every response with a 2XX status is considered successful.

PR: #2

**Comment by NikolaiGulatz** [comment]
#2

**Comment by vincenzor** [comment]
Hi @NikolaiGulatz. Thx for the fix. I've merged your PR.
